services:
  mattermost:
    depends_on: [postgres]
    image: mattermost/mattermost-team-edition:10.4
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    pids_limit: 200
    read_only: false
    tmpfs: [/tmp]
    ports:
      - 8065:8065
      - 8443:8443/udp
      - 8443:8443/tcp
    volumes:
      - ./volumes/mattermost/config:/mattermost/config:rw
      - ./volumes/mattermost/data:/mattermost/data:rw
      - ./volumes/mattermost/logs:/mattermost/logs:rw
      - ./volumes/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/mattermost/client/plugins:/mattermost/client/plugins:rw
      - ./volumes/mattermost/bleve-indexes:/mattermost/bleve-indexes:rw
    environment:
      # timezone inside container
      TZ: America/Chicago

      # necessary Mattermost options/variables (see env.example)
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://mmuser:mmuser_password@postgres:5432/mattermost?sslmode=disable&connect_timeout=10

      # necessary for bleve
      MM_BLEVESETTINGS_INDEXDIR: /mattermost/bleve-indexes

      # additional settings
      MM_SERVICESETTINGS_SITEURL: http://127.0.0.1:8065


  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
    environment:
      # timezone inside container
      TZ: America/Chicago

      # necessary Postgres options/variables
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: mmuser_password
      POSTGRES_DB: mattermost